### ISSUE TITLE
Problem with tintColor and UIAppearance

### ISSUE THREAD

**Issue by txaiwieser** [Instabug/Instabug-iOS#256]
### Steps to Reproduce the Problem
Configure instabug:
        Instabug.setColorTheme(.light)
        Instabug.setPrimaryColor(.colorBlack)

Activate floating button
### Expected Behavior
Navigation tintColot being the same as set on the PrimaryColor

### Actual Behavior
![simulator_screen_shot_-_iphone_x_-_2018-05-26_at_15_04_04](https://user-images.githubusercontent.com/2997313/40579117-106342d0-60f7-11e8-9ba4-72c4b969749e.png)

### SDK Version
Latest
### iOS Version
Latest
### Device Type
Any

**Comment by Kmohamed** [comment]
Let me check it and get back to you

**Comment by Kmohamed** [comment]
@txaiwieser are you setting a tint color for navigation bar using UIAppearance ?

**Comment by txaiwieser** [comment]
@Kmohamed Yes, our app has global navigation bar tintColor set to white. But instabug shouldn't follow this, right?

You can do something like this to avoid using app appearance:
`UINavigationBar.appearance(whenContainedInInstancesOf: [InstabugViewController.self]).tintColor = nil`

**Comment by Kmohamed** [comment]
Yes, you’re right we are working on a fix for this bug 🐛

**Comment by lovluv** [comment]
[https://mailguru.s3.amazonaws.com/images/spark/qr.v2/845098b9bd69458ab9234fb1467b3ce1.png]

Lydia Ugarte está de acuerdo.




Spark by Readdle<https://sparkmailapp.com/appstore>

**Comment by yousefhamza** [comment]
Hi @txaiwieser,
I couldn't reproduce this with `UINavigationBar.appearance().tintColor = .white`, however I did reproduce it with `UIBarButtonItem.appearance().tintColor = .white`

Can you please verify that this is actually the issue your having not the `UINavigationBar`?

**Comment by yousefhamza** [comment]
Hi again,
I made this custom build for you to verify that it fixes your problem
`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'fix/nav_bar_appearance'`

**Comment by txaiwieser** [comment]
It didn't work :(
Just debug further and the exactly line of UIAppearance that is causing the bug its this one: 
`UIButton.appearance(whenContainedInInstancesOf: [UINavigationBar.self]).tintColor = .white`

**Comment by yousefhamza** [comment]
Will check it again with your new input and get back to you.

**Comment by yousefhamza** [comment]
I pushed a fix for you on the same branch, re-run pod install with the same pod to get it.
`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'fix/nav_bar_appearance'`

**Comment by txaiwieser** [comment]
Still having the same problem. It now starts the write color but it changes back.

https://www.dropbox.com/s/zua577d9qvy1tud/instabugbug.mov?dl=0

**Comment by yousefhamza** [comment]
Please make sure that you have updated your pods, I have also uploaded a sample app for you (you will find it in the Sample directory) that has the code you provided so far and that it works too. let us know If there's appearance code that caused the issue so we can better help you.

https://www.dropbox.com/s/f8oze5znumck3ni/Sample.zip?dl=0

**Comment by Kmohamed** [comment]
@txaiwieser did you manage to check youssef sample app ?

**Comment by Kmohamed** [comment]
@txaiwieser any updates regarding this issue ?

**Comment by txaiwieser** [comment]
Sorry, we're at WWDC, so busy week. Going to take a look a soon as possible 👍

**Comment by Kmohamed** [comment]
@txaiwieser  no problem, did you enjoy it ?

**Comment by txaiwieser** [comment]
@Kmohamed It was awesome! Had a really great time there! 

I just did some some more testing with the latest build from your branch and it seems to be working fine!

Didn't experience any glitches on the nav bar tintColor

👍

**Comment by Kmohamed** [comment]
Great 👍 i will update you once released
