### ISSUE TITLE
crash: Parent NSManagedObjectContext must not be nil.

### ISSUE THREAD

**Issue by kim-harry** [Instabug/Instabug-iOS#367]
### Steps to Reproduce the Problem
it's a user case... i don't know actually how can reproduce that. 
But, App try to send http request with the Instabug integrated, and server say that request received well but there are no Instabug logs for that.

99% of requests and responses logs well. Except just before crash. 

### Expected Behavior
don't crash
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
9.1.2

### iOS Version
13.4.1

### Device Model
iPhone 8 Plus

### [Optional] Project That Reproduces the Issue

Parent NSManagedObjectContext must not be nil.
_68-[IBGConsoleLogger loadSnapshotWithSessionId:withCompletionHandler:]_block_invoke (IBGConsoleLogger.m:154)

data:text/text;charset=utf-8,
# Cause: Parent NSManagedObjectContext must not be nil.
# Reported at: 2020-04-28 19:42:41 UTC

Thread 0 [Crashed]:

0    CoreFoundation                           0x1a1a215f0     _exceptionPreprocess + 224
1    libobjc.A.dylib                          0x1a1743bcc     objc_exception_throw + 55
2    CoreData                                 0x1a63bacb4     -[NSManagedObjectContext setParentContext:] + 303
3    Instabug                                 0x101ff50f8     _68-[IBGConsoleLogger loadSnapshotWithSessionId:withCompletionHandler:]_block_invoke (IBGConsoleLogger.m:154)
4    Instabug                                 0x10215b4f0     _43-[IBGDALService readASync:completionBlock:]_block_invoke (IBGDALService.m:0)
5    CoreData                                 0x1a6464794     developerSubmittedBlockToNSManagedObjectContextPerform + 155
6    libdispatch.dylib                        0x1a16e7524     _dispatch_client_callout + 15
7    libdispatch.dylib                        0x1a16c4b3c     _dispatch_lane_serial_drain$VARIANT$armv81 + 563
8    libdispatch.dylib                        0x1a16c554c     _dispatch_lane_invoke$VARIANT$armv81 + 395
9    libdispatch.dylib                        0x1a16ce84c     _dispatch_workloop_worker_thread + 579
10   libsystem_pthread.dylib                  0x1a1738b74     _pthread_wqthread + 271
11   libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

**Comment by Kmohamed** [comment]
Hello @kim-harry 
We are sorry for the inconvenience. Related to this
> But, App try to send http request with the Instabug integrated, and server say that request received well but there are no Instabug logs for that.

Do you mean that this crash occurs after sending a request to your server? Also, could you share with me the complete stack trace?

**Comment by kim-harry** [comment]
Thanks for quick response!

> Do you mean that this crash occurs after sending a request to your server? Also, could you share with me the complete stack trace?

I'm not sure for this, but I think that. 

The complete stack trace follows. I just replace application name to "MyApp".

data:text/text;charset=utf-8,
# Cause: Parent NSManagedObjectContext must not be nil.
# Reported at: 2020-04-28 19:42:41 UTC

Thread 0 [Crashed]:

0    CoreFoundation                           0x1a1a215f0     _exceptionPreprocess + 224
1    libobjc.A.dylib                          0x1a1743bcc     objc_exception_throw + 55
2    CoreData                                 0x1a63bacb4     -[NSManagedObjectContext setParentContext:] + 303
3    Instabug                                 0x101ff50f8     _68-[IBGConsoleLogger loadSnapshotWithSessionId:withCompletionHandler:]_block_invoke (IBGConsoleLogger.m:154)
4    Instabug                                 0x10215b4f0     _43-[IBGDALService readASync:completionBlock:]_block_invoke (IBGDALService.m:0)
5    CoreData                                 0x1a6464794     developerSubmittedBlockToNSManagedObjectContextPerform + 155
6    libdispatch.dylib                        0x1a16e7524     _dispatch_client_callout + 15
7    libdispatch.dylib                        0x1a16c4b3c     _dispatch_lane_serial_drain$VARIANT$armv81 + 563
8    libdispatch.dylib                        0x1a16c554c     _dispatch_lane_invoke$VARIANT$armv81 + 395
9    libdispatch.dylib                        0x1a16ce84c     _dispatch_workloop_worker_thread + 579
10   libsystem_pthread.dylib                  0x1a1738b74     _pthread_wqthread + 271
11   libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 1:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    CoreFoundation                           0x1a199f3b4     _CFRunLoopServiceMachPort + 147
2    CoreFoundation                           0x1a199a3e8     _CFRunLoopRun + 1159
3    CoreFoundation                           0x1a1999c34     CFRunLoopRunSpecific + 423
4    GraphicsServices                         0x1abae338c     GSEventRunModal + 159
5    UIKitCore                                0x1a5acc22c     UIApplicationMain + 1931
6    MyApp                        0x100c49474     main (AppDelegate.swift:24)
7    libdyld.dylib                            0x1a1821800     $start + 3

Thread 2:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    CoreFoundation                           0x1a199f3b4     _CFRunLoopServiceMachPort + 147
2    CoreFoundation                           0x1a199a3e8     _CFRunLoopRun + 1159
3    CoreFoundation                           0x1a1999c34     CFRunLoopRunSpecific + 423
4    Foundation                               0x1a1cdcbcc     -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 227
5    Foundation                               0x1a1cdcaac     -[NSRunLoop(NSRunLoop) runUntilDate:] + 87
6    UIKitCore                                0x1a5b6e160     -[UIEventFetcher threadMain] + 151
7    Foundation                               0x1a1e0b9d0     _NSThread__start__ + 847
8    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
9    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 3:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    MyApp                        0x100f5e22c     CLSMachExceptionServer + 99
2    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
3    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 4:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    CoreFoundation                           0x1a199f3b4     _CFRunLoopServiceMachPort + 147
2    CoreFoundation                           0x1a199a3e8     _CFRunLoopRun + 1159
3    CoreFoundation                           0x1a1999c34     CFRunLoopRunSpecific + 423
4    CoreFoundation                           0x1a199a990     CFRunLoopRun + 59
5    CoreMotion                               0x1ae5ff188     0x000000018d077187 + 1095
6    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
7    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 5:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    Instabug                                 0x102192170     exception_server_thread + 1207
2    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
3    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 6:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    CoreFoundation                           0x1a199f3b4     _CFRunLoopServiceMachPort + 147
2    CoreFoundation                           0x1a199a3e8     _CFRunLoopRun + 1159
3    CoreFoundation                           0x1a1999c34     CFRunLoopRunSpecific + 423
4    CFNetwork                                0x1a4c5ec44     0x00000001836d6c43 + 191
5    Foundation                               0x1a1e0b9d0     _NSThread__start__ + 847
6    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
7    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 7:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    CoreFoundation                           0x1a199f3b4     _CFRunLoopServiceMachPort + 147
2    CoreFoundation                           0x1a199a3e8     _CFRunLoopRun + 1159
3    CoreFoundation                           0x1a1999c34     CFRunLoopRunSpecific + 423
4    CFNetwork                                0x1a4c5ec44     0x00000001836d6c43 + 191
5    Foundation                               0x1a1e0b9d0     _NSThread__start__ + 847
6    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
7    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 8:

0    libsystem_kernel.dylib                   0x1a1817014     _select + 8
1    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
2    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 9:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    CoreFoundation                           0x1a199f3b4     _CFRunLoopServiceMachPort + 147
2    CoreFoundation                           0x1a199a3e8     _CFRunLoopRun + 1159
3    CoreFoundation                           0x1a1999c34     CFRunLoopRunSpecific + 423
4    AVFAudio                                 0x1ae7425dc     GenericRunLoopThread::Entry(void*) + 155
5    AVFAudio                                 0x1ae793300     CAPThread::Entry(CAPThread*) + 203
6    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
7    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 10:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    CoreFoundation                           0x1a199f3b4     _CFRunLoopServiceMachPort + 147
2    CoreFoundation                           0x1a199a3e8     _CFRunLoopRun + 1159
3    CoreFoundation                           0x1a1999c34     CFRunLoopRunSpecific + 423
4    Foundation                               0x1a1cdcbcc     -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 227
5    libAXSpeechManager.dylib                 0x1c53d3e78     -[AXSpeechThread main] + 371
6    Foundation                               0x1a1e0b9d0     _NSThread__start__ + 847
7    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
8    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 11:

0    libsystem_kernel.dylib                   0x1a17f5198     mach_msg_trap + 8
1    CoreFoundation                           0x1a199f3b4     _CFRunLoopServiceMachPort + 147
2    CoreFoundation                           0x1a199a3e8     _CFRunLoopRun + 1159
3    CoreFoundation                           0x1a1999c34     CFRunLoopRunSpecific + 423
4    AudioToolbox                             0x1acccb4d4     GenericRunLoopThread::Entry(void*) + 155
5    libAudioToolboxUtility.dylib             0x1acd8c614     0x1acd7d000
6    libsystem_pthread.dylib                  0x1a1737d98     _pthread_start + 155
7    libsystem_pthread.dylib                  0x1a173b74c     thread_start + 7

Thread 12:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 13:

0    libsystem_kernel.dylib                   0x1a17f51d4     $semaphore_wait_trap + 8
1    libdispatch.dylib                        0x1a16b98c8     _dispatch_semaphore_wait_slow + 127
2    libswiftDispatch.dylib                   0x1d7edc9e4     OS_dispatch_semaphore.wait(wallTimeout:) + 19
3    Mixpanel                                 0x1027171a4     Flush.flushQueueInBatches(_:type:) (Flush.swift:160)
4    Mixpanel                                 0x1027160d0     Flush.flushEventsQueue(_:automaticEventsEnabled:) (Flush.swift:88)
5    Mixpanel                                 0x1027542e4     closure #1 in closure #1 in MixpanelInstance.flush(completion:) (MixpanelInstance.swift:1152)
6    Mixpanel                                 0x102746d34     thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>:0)
7    libdispatch.dylib                        0x1a16e69a8     _dispatch_call_block_and_release + 23
8    libdispatch.dylib                        0x1a16e7524     _dispatch_client_callout + 15
9    libdispatch.dylib                        0x1a16c4b3c     _dispatch_lane_serial_drain$VARIANT$armv81 + 563
10   libdispatch.dylib                        0x1a16c554c     _dispatch_lane_invoke$VARIANT$armv81 + 395
11   libdispatch.dylib                        0x1a16ce84c     _dispatch_workloop_worker_thread + 579
12   libsystem_pthread.dylib                  0x1a1738b74     _pthread_wqthread + 271
13   libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 14:

0    libsystem_pthread.dylib                  0x1a173b738     $start_wqthread + 0

Thread 15:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 16:

0    libsystem_kernel.dylib                   0x1a181777c     _ulock_wait + 8
1    libdispatch.dylib                        0x1a16b9a10     _dispatch_group_wait_slow + 51
2    MyApp                        0x100efa310     closure #5 in CPCaptureData.submit(parentProgress:params:options:completionHandler:) (CPCaptureData + ICPSubmittable.swift:372)
3    MyApp                        0x100ea392c     thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>:0)
4    libdispatch.dylib                        0x1a16cadd0     _dispatch_block_async_invoke2 + 103
5    libdispatch.dylib                        0x1a16e7524     _dispatch_client_callout + 15
6    libdispatch.dylib                        0x1a16c4b3c     _dispatch_lane_serial_drain$VARIANT$armv81 + 563
7    libdispatch.dylib                        0x1a16c554c     _dispatch_lane_invoke$VARIANT$armv81 + 395
8    libdispatch.dylib                        0x1a16ce84c     _dispatch_workloop_worker_thread + 579
9    libsystem_pthread.dylib                  0x1a1738b74     _pthread_wqthread + 271
10   libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 17 [Crashed]:

0    libsystem_kernel.dylib                   0x1a1816d88     _pthread_kill + 8
1    libsystem_c.dylib                        0x1a1682644     abort + 99
2    Instabug                                 0x1021b0f54     uncaught_exception_handler.cold.1 + 27
3    Instabug                                 0x102185600     uncaught_exception_handler + 59
4    CoreFoundation                           0x1a1a218f8     _handleUncaughtException + 635
5    libobjc.A.dylib                          0x1a1743e74     _objc_terminate() + 111
6    MyApp                        0x100f70a0c     CLSTerminateHandler() + 347
7    libc++abi.dylib                          0x1a17ea14c     $std::__terminate(void (*)()) + 15
8    libc++abi.dylib                          0x1a17ea0e4     $std::terminate() + 43
9    libdispatch.dylib                        0x1a16e7538     _dispatch_client_callout + 35
10   libdispatch.dylib                        0x1a16c4b3c     _dispatch_lane_serial_drain$VARIANT$armv81 + 563
11   libdispatch.dylib                        0x1a16c554c     _dispatch_lane_invoke$VARIANT$armv81 + 395
12   libdispatch.dylib                        0x1a16ce84c     _dispatch_workloop_worker_thread + 579
13   libsystem_pthread.dylib                  0x1a1738b74     _pthread_wqthread + 271
14   libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 18:

0    libsystem_malloc.dylib                   0x1a1704fa4     nanov2_allocate_from_block$VARIANT$armv81 + 232
1    libsystem_malloc.dylib                   0x1a170434c     nanov2_allocate$VARIANT$armv81 + 123
2    libsystem_malloc.dylib                   0x1a1704280     nanov2_malloc$VARIANT$armv81 + 59
3    libsystem_malloc.dylib                   0x1a17116c0     malloc_zone_malloc + 155
4    libsystem_malloc.dylib                   0x1a17120cc     malloc + 27
5    libboringssl.dylib                       0x1a6965b84     0x1a68ea000
6    libboringssl.dylib                       0x1a6943b38     0x1a68ea000
7    libboringssl.dylib                       0x1a6943c24     0x1a68ea000
8    libboringssl.dylib                       0x1a692ada0     0x1a68ea000
9    libboringssl.dylib                       0x1a692afb4     0x1a68ea000
10   libboringssl.dylib                       0x1a693bdf0     0x1a68ea000
11   libboringssl.dylib                       0x1a6967f34     0x1a68ea000
12   libboringssl.dylib                       0x1a693d634     0x1a68ea000
13   libboringssl.dylib                       0x1a68f2bfc     0x1a68ea000
14   libboringssl.dylib                       0x1a68fa420     0x1a68ea000
15   libboringssl.dylib                       0x1a68fb27c     0x1a68ea000
16   libboringssl.dylib                       0x1a68fb668     0x1a68ea000
17   libusrtcp.dylib                          0x1a6d47f30     0x1a6d2a000
18   libusrtcp.dylib                          0x1a6d37410     0x1a6d2a000
19   libnetwork.dylib                         0x1a3e3d41c     nw_channel_add_input_frames + 4531
20   libnetwork.dylib                         0x1a3e3c1ec     nw_channel_update_input_source + 167
21   libnetwork.dylib                         0x1a3e3ba20     _nw_channel_create_block_invoke.22 + 43
22   libdispatch.dylib                        0x1a16e7524     _dispatch_client_callout + 15
23   libdispatch.dylib                        0x1a16c1274     _dispatch_continuation_pop$VARIANT$armv81 + 403
24   libdispatch.dylib                        0x1a16d1410     _dispatch_source_invoke$VARIANT$armv81 + 1219
25   libdispatch.dylib                        0x1a16c65e8     _dispatch_workloop_invoke$VARIANT$armv81 + 1543
26   libdispatch.dylib                        0x1a16ce84c     _dispatch_workloop_worker_thread + 579
27   libsystem_pthread.dylib                  0x1a1738b74     _pthread_wqthread + 271
28   libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 19:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 20:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 21:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 22:

0    CoreFoundation                           0x1a19034e8     -[__NSDictionaryM setObject:forKeyedSubscript:] + 868
1    Instabug                                 0x101ffa988     -[IBGCrash send] (IBGCrash.m:210)
2    Instabug                                 0x1020fc5f0     closure #1 in IBGCrashManager.sendExceptionAsCrash(with:userInfo:) (IBGCrashManager.swift:238)
3    Instabug                                 0x1020fc3c0     thunk for @escaping @callee_guaranteed (@in_guaranteed Any?) -> () (<compiler-generated>:0)
4    Instabug                                 0x102139c14     -[IBGProgress addCompletionHandler:] (IBGProgress.m:49)
5    Instabug                                 0x1020fc88c     IBGCrashManager.sendExceptionAsCrash(with:userInfo:) + 571
6    Instabug                                 0x1020fa998     closure #1 in IBGCrashManager.reportException(with:) (IBGCrashManager.swift:99)
7    Instabug                                 0x1020fa9fc     thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>:0)
8    libdispatch.dylib                        0x1a16e69a8     _dispatch_call_block_and_release + 23
9    libdispatch.dylib                        0x1a16e7524     _dispatch_client_callout + 15
10   libdispatch.dylib                        0x1a16c4b3c     _dispatch_lane_serial_drain$VARIANT$armv81 + 563
11   libdispatch.dylib                        0x1a16c554c     _dispatch_lane_invoke$VARIANT$armv81 + 395
12   libdispatch.dylib                        0x1a16ce84c     _dispatch_workloop_worker_thread + 579
13   libsystem_pthread.dylib                  0x1a1738b74     _pthread_wqthread + 271
14   libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 23:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 24:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 25:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 26:

0    libsystem_kernel.dylib                   0x1a1819768     $stat + 8
1    libsqlite3.dylib                         0x1a3655a00     0x00000001820cd9ff + 1039
2    libsqlite3.dylib                         0x1a3654bd4     0x00000001820ccbd3 + 543
3    libsqlite3.dylib                         0x1a3674128     0x00000001820ec127 + 3495
4    libsqlite3.dylib                         0x1a3671e9c     $sqlite3_step + 735
5    MyApp                        0x101014ca8     -[APMSqliteStore numberForQuery:parameterValues:error:] + 179
6    MyApp                        0x100ffc100     -[APMRemoteConfig lastRemoteConfigUpdateTimestamp] + 155
7    MyApp                        0x100ffbfe8     -[APMRemoteConfig isExpired] + 183
8    MyApp                        0x100fe7b74     -[APMMeasurement uploadData] + 331
9    MyApp                        0x100ff46c8     _49-[APMMeasurement handleAppWillResignActiveEvent:]_block_invoke_3 + 35
10   MyApp                        0x100ffee94     _51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 43
11   libdispatch.dylib                        0x1a16e69a8     _dispatch_call_block_and_release + 23
12   libdispatch.dylib                        0x1a16e7524     _dispatch_client_callout + 15
13   libdispatch.dylib                        0x1a16c4b3c     _dispatch_lane_serial_drain$VARIANT$armv81 + 563
14   libdispatch.dylib                        0x1a16c554c     _dispatch_lane_invoke$VARIANT$armv81 + 395
15   libdispatch.dylib                        0x1a16ce84c     _dispatch_workloop_worker_thread + 579
16   libsystem_pthread.dylib                  0x1a1738b74     _pthread_wqthread + 271
17   libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 27:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 28:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 29:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 30:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Thread 31:

0    libsystem_kernel.dylib                   0x1a1817940     _workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x1a173b740     $start_wqthread + 7

Binary Images:

0x1a18f7000     CoreFoundation                               arm64      409609CD-8410-38E1-BA5D-BDED609D2018 
0x1a173e000     libobjc.A.dylib                              arm64      091241F8-E94C-39BA-9CA6-7352E998BB41 
0x1a632c000     CoreData                                     arm64      A654D396-B79C-3F46-9E3F-BE9EC0EE1AF4 
0x101f40000     Instabug                                     arm64      71DA52B4-DD17-3191-8DEC-93EFD3D83D8D 
0x1a168c000     libdispatch.dylib                            arm64      5A83D0CF-8FB9-3727-8A32-012D20A47EC8 
0x1a172d000     libsystem_pthread.dylib                      arm64      FB1DD49F-0CFB-3114-BDB4-0EF7BE44F6BC 
0x1a17f1000     libsystem_kernel.dylib                       arm64      B422BA38-A9F6-3062-BE28-D28D39E3FE25 
0x1abae0000     GraphicsServices                             arm64      AEA26BF9-4837-39A2-9902-950B92B52592 
0x1a50a0000     UIKitCore                                    arm64      3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 
0x100c44000     MyApp                            arm64      48AD625F-6BEA-3A61-AE35-267B80F2BA63 
0x1a1820000     libdyld.dylib                                arm64      876FB49A-BFBA-37BF-AD37-6FFC90F7F981 
0x1a1cd5000     Foundation                                   arm64      1A46239D-F2FC-34B6-95BC-9F38869F0C85 
0x1ae515000     CoreMotion                                   arm64      70ED3EF1-D826-3D55-B5EA-E657AC5E8057 
0x1a4c5d000     CFNetwork                                    arm64      C4865497-192B-3DBE-81E9-84A99B788ADF 
0x1ae6dd000     AVFAudio                                     arm64      1DF33123-9535-3945-983F-B139A4216FA9 
0x1c53c8000     libAXSpeechManager.dylib                     arm64      0EC202B2-5E95-39BF-AF0C-1624320330E9 
0x1acb48000     AudioToolbox                                 arm64      9EEA0978-FCAD-33CC-9E30-35EA939B2143 
0x1acd7d000     libAudioToolboxUtility.dylib                 arm64      5E0EC0BF-47F0-3853-A777-EA0123CDECAA 
0x1d7ed7000     libswiftDispatch.dylib                       arm64      96F8DBD7-431C-38EC-9B64-36E82A2C3A36 
0x1026f0000     Mixpanel                                     arm64      A14D59B8-3982-3BDB-91DD-D6210031B3BD 
0x1a1610000     libsystem_c.dylib                            arm64      8D39FF48-E14C-3F86-8E10-90F54896BB65 
0x1a17d8000     libc++abi.dylib                              arm64      F07199AC-8A90-3127-B17F-0A906FFB7302 
0x1a1701000     libsystem_malloc.dylib                       arm64      A0A7D67A-F0F3-399A-8F00-6F92716D8E6F 
0x1a68ea000     libboringssl.dylib                           arm64      E764C033-B426-3761-8FE5-22445B621FCF 
0x1a6d2a000     libusrtcp.dylib                              arm64      10FE0FAF-8A4D-3BCF-BC43-E8A951656957 
0x1a3c57000     libnetwork.dylib                             arm64      CF9B76BF-435B-38D2-AED3-FB2C050D9216 
0x1a362f000     libsqlite3.dylib                             arm64      4FADB9EE-56A7-3AFC-A360-4780DDF3411B

**Comment by Kmohamed** [comment]
Thanks a lot. this is more than enough. I think we already aware of this issue and here is a custom build that will fix this crash. Also, I curios to know the number of occurrences.
`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'custom-purge-logs'`
And this fix should be released very soon. I will update you anyway.

**Comment by kim-harry** [comment]
Thanks for update. I will wait for new release.

**Comment by kim-harry** [comment]
> Also, I curios to know the number of occurrences.

Just one case happened yet. It is very rare case.

**Comment by Kmohamed** [comment]
Thank you Kim 🙏

**Comment by navyseai** [comment]
I quickly need a fix on this its happening alot to our app
70 crashes per day

**Comment by Kmohamed** [comment]
@navyseai We are sorry for the inconvenience. You can use this custom build until we release a fix for it.
`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'custom-purge-logs'`

**Comment by Kmohamed** [comment]
@navyseai Please tell me if this custom build fixes your issue.

**Comment by RamblinWreck77** [comment]
I ran into this as well. Trying the custom build for our next release but that won't be for several days.

**Comment by navyseai** [comment]
@Kmohamed sorry but since i cannot replicate it i cannot say if it solves the problem is happening to our users. we currently have 1K crashes in 300 users in 10-15 days in what seems to be all devices 82% is using ios 13

Any idea on when that solution might be approved?

this is our biggest bug

**Comment by Kmohamed** [comment]
@navyseai Are you able to use the custom build? it will fix the issue.

**Comment by navyseai** [comment]
@Kmohamed we cannot put a custom build into production

**Comment by Kmohamed** [comment]
Actually, the official release will be next Thursday. Does this works fine with you?

**Comment by navyseai** [comment]
@Kmohamed yes, thanks

**Comment by Kmohamed** [comment]
This has been fixed in 9.1.3 Please feel free to reopen if you encountered the same issue again.
Thank You.

**Comment by navyseai** [comment]
We've updated the app to use the new instabug 9.1.3 and we are still getting the same issue. It just seems to have changed line from 155 to 156(?)

We need a fix quickly on this this is happening allot on our users and its a major problem. This is happening to the same user sometimes 10 times in a week.

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1955f55f0 __exceptionPreprocess
1  libobjc.A.dylib                0x195317bcc objc_exception_throw
2  CoreData                       0x199f8ecb4 -[NSMappingModel initWithContentsOfURL:]
3  Instabug                       0x10446ab44 _hidden#6747_ + 156 (__hidden#6765_:156)
4  Instabug                       0x1045d23a0 _hidden#19958_ + 148 (__hidden#19991_:148)
5  CoreData                       0x19a038794 developerSubmittedBlockToNSManagedObjectContextPerform
6  libdispatch.dylib              0x1952bb524 _dispatch_client_callout
7  libdispatch.dylib              0x195298b3c _dispatch_lane_serial_drain$VARIANT$armv81
8  libdispatch.dylib              0x19529954c _dispatch_lane_invoke$VARIANT$armv81
9  libdispatch.dylib              0x1952a284c _dispatch_workloop_worker_thread
10 libsystem_pthread.dylib        0x19530cb74 _pthread_wqthread
11 libsystem_pthread.dylib        0x19530f740 start_wqthread
```

**Comment by Kmohamed** [comment]
@navyseai I am sorry for experiencing this crash again. But are you sure that this crash from the new build, not the old one?

**Comment by navyseai** [comment]
@Kmohamed yes

**Comment by Kmohamed** [comment]
@navyseai I am very sorry for inconvenience. We will do some investigation and get back to you very soon.

**Comment by Kmohamed** [comment]
This crash fixed on 9.1.4
Sorry for inconvenience 🙏

**Comment by navyseai** [comment]
come on guys....we just updated

Crashed: NSManagedObjectContext 0x1560f7c0
0  libdispatch.dylib              0x1cddd836 dispatch_group_leave + 99
1  Instabug                       0x131906d _hidden#5932_ + 100 (__hidden#5985_:100)
2  Instabug                       0x14084c9 _hidden#15319_ + 108 (__hidden#15341_:108)
3  Instabug                       0x1408337 _hidden#15316_ + 90 (__hidden#15341_:90)
4  Instabug                       0x140818f _hidden#15312_ + 82 (__hidden#15341_:82)
5  Instabug                       0x1408311 _hidden#15315_ + 89 (__hidden#15341_:89)
6  Instabug                       0x142ad57 _hidden#17218_ + 336 (__hidden#17272_:336)
7  Instabug                       0x142a6b5 _hidden#17214_ + 275 (__hidden#17272_:275)
8  Instabug                       0x146c765 _hidden#19991_ + 148 (__hidden#20024_:148)
9  CoreData                       0x1f71f17b developerSubmittedBlockToNSManagedObjectContextPerform + 230
10 libdispatch.dylib              0x1cde659d _dispatch_queue_serial_drain + 854
11 libdispatch.dylib              0x1cddcb71 _dispatch_queue_invoke + 886
12 libdispatch.dylib              0x1cde6a1f _dispatch_queue_override_invoke + 282
13 libdispatch.dylib              0x1cde81b5 _dispatch_root_queue_drain + 326
14 libdispatch.dylib              0x1cde800f _dispatch_worker_thread3 + 106
15 libsystem_pthread.dylib        0x1cf8e87d _pthread_wqthread + 1040
16 libsystem_pthread.dylib        0x1cf8e45c start_wqthread + 8

its been weeks now
this time we didnt even reach production

**Comment by Kmohamed** [comment]
@navyseai 
We are very sorry about this. But I think this is a new one. I am curious to know if you are using CoreData maybe a conflict somehow?

**Comment by navyseai** [comment]
no, we are using Realm (4.3.2)

**Comment by Kmohamed** [comment]
Thanks for your help.
Could you share with me the full crash including the UUID of Instabug? to be able to remove the hidden frames.

**Comment by Kmohamed** [comment]
Thank you

**Comment by Kmohamed** [comment]
Could you share with me Instabug load address?

**Comment by navyseai** [comment]
[crashInstabugLog.txt](https://github.com/Instabug/Instabug-iOS/files/4793259/crashInstabugLog.txt)

**Comment by Kmohamed** [comment]
I mean this one
<img width="805" alt="Screen Shot 2020-06-17 at 4 50 58 PM" src="https://user-images.githubusercontent.com/1115748/84913400-cdb7c580-b0ba-11ea-8599-606c510e52f0.png">

**Comment by navyseai** [comment]
Will this be enough?

[instabug_crash.txt.zip](https://github.com/Instabug/Instabug-iOS/files/4793681/instabug_crash.txt.zip)

**Comment by Kmohamed** [comment]
Perfect 👌

**Comment by Kmohamed** [comment]
@navyseai The UUID does not match the released one. So I think this one from an application on TestFlight. so Could you share with me a DSYM file matches this UUID `b767399b44cd3937bbc72b49d439b40e` ?

**Comment by AmyNgithub** [comment]
I think we have a similar issue in our app, however it has only occurred for two of our users so far and I have not been able to reproduced it yet.

**Comment by Kmohamed** [comment]
Hello @AmyNgithub we are very sorry for inconvenience. Could you provide me with SDK version?

**Comment by AmyNgithub** [comment]
We're currently using 9.1.2. See in the thread that you have updated since then. I will try to update the SDK. However since I have not been able to reproduce it I will not be able to verify that it solves the issue. I'll follow the development of the issue in this thread and update when I know more.

**Comment by AmyNgithub** [comment]
@navyseai Do you know how the crash is triggered in your app? Thought it might give me a hint on how to reproduce it in my app.

**Comment by Kmohamed** [comment]
Totally agree with you 👍
I succeeded to reproduce it but with code injection. It’s something related to saving data in CoreData while application going to the background also adding Data protection may increase the probability of this crash. It should be fixed on 9.1.5. I will leave this issue open until we 100% that there is nothing else that could cause this crash.

**Comment by navyseai** [comment]
> @navyseai Do you know how the crash is triggered in your app? Thought it might give me a hint on how to reproduce it in my app.

We were only able to reproduce it once. It seemed it was happening when we attempt to send 2 reports for instabug. But joining that with what Kmohamed said i would try to alternate to background while sending the report or something like that.
