### ISSUE TITLE
Experiencing High Number of Crashes on 10.4.4

### ISSUE THREAD

**Issue by rajanbalana** [Instabug/Instabug-iOS#418]
![image](https://user-images.githubusercontent.com/13097169/117842339-75be1a80-b29b-11eb-8a12-f3cde732942f.png)

**Comment by rajanbalana** [comment]
What is the ETA for the official release with the fix?

**Comment by yousefhamza** [comment]
First week of June

**Comment by shalinipk** [comment]
Seeing app crashes - I am on instabug 10.4.4. @yousefhamza is this related to the original post ? 

Thanks!

```
data:text/text;charset=utf-8,
# Cause: Crash due to signal: SIGBUS(BUS_ADRERR) at 10bf08000
# Reported at: 2021-05-19 19:39:22 UTC

Thread 0 [Crashed]:

0    libsystem_platform.dylib                 0x1c95461e0     _platform_memmove + 256
1    Instabug                                 0x1077e9cdc     _cxa_throw_decorator (PLCxaThrowSwapper.c:110)
2    libobjc.A.dylib                          0x1950b5c7c     objc_exception_throw + 351
3    CoreFoundation                           0x180c436e4     -[NSException raise] + 11
4    Foundation                               0x181eefca8     -[NSObject(NSKeyValueCoding) setValue:forKey:] + 311
5    UIKitCore                                0x1831e0728     -[UINibKeyValuePair apply] + 47
```

**Comment by shalinipk** [comment]
I downgraded to 10.4.3 - not seeing the crash anymore

**Comment by rajanbalana** [comment]
Thanks for the prompt response. Does v10.5.1 contains the fix for the crash in context?

**Comment by AhmedOS** [comment]
Hi @shalinipk , the crash you are reporting is fixed in v10.5.1, but it isn't related to the crash in this issue.


Hi @rajanbalana , the fix for the crash will be available in the next release on first week of June.

**Comment by shalinipk** [comment]
Thanks @AhmedOS

 I did try upgrading to 10.5.1 - however that did not resolve the crash :(

**Comment by AhmedOS** [comment]
@shalinipk 
We are sorry for the inconvenience. Would you please try the latest release v10.5.2? It has a further fix for that issue.
If the issue remains, please open a new issue with reproduction steps.

**Comment by yousefhamza** [comment]
Hi @shalinipk,
Can you reproduce this crash locally? If so can you send us a sample project? 🙏

**Comment by rajanbalana** [comment]
@yousefhamza Any update on the release for the crash fix?

**Comment by yousefhamza** [comment]
Hi @rajanbalana, it's happening next week 🙏

**Comment by rajanbalana** [comment]
Any update on the release?

**Comment by rajanbalana** [comment]
@yousefhamza Can you please share an update on this issue?

**Comment by yousefhamza** [comment]
@rajanbalana thank you for your patience, we will release a fix for this next Monday 👍

**Comment by yousefhamza** [comment]
Fix released in 10.7.2 🎉 

@rajanbalana thanks for the report and your patience 🙏
